### ISSUE TITLE
Rubocop configuration is out-of-date

### ISSUE THREAD

**Issue by danielwestendorf** [Skookum/bamboozled#16]
```
$ bundle exec rubocop lib/bamboozled/api/employee.rb
bamboozled/.rubocop.yml: Lint/SpaceBeforeFirstArg has the wrong namespace - should be Style
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
(obsolete configuration found in bamboozled/.rubocop.yml, please update it)
```

From my Gemfile.lock
`rubocop (0.37.2)`

It looks like a number of the cops have been changed with the latest version of rubocop, while no version of rubocop is specified in the Gemfile. I updated the cops on my local box, and when it was finally running the existing project 32 offenses.

Depending on which direction the project want to take, I think the resolution here is to either 
- update the rubocop config to support the latest version of rubocop
- specify the rubocop gem version

**Comment by danielwestendorf** [comment]
Well, I thought #17 would fix the hound problems, but perhaps not. It still fails without comments.

**Comment by Enriikke** [comment]
Thanks for the work on this @danielwestendorf. I've added a fix for Rubocop and Hound. It should all work once merged so I'll be closing this issue. :+1:
