### ISSUE TITLE
Team and subTeam

### ISSUE THREAD

**Issue by kamyk** [Skookum/bamboozled#19]
Hello,

I'm using BambooHR API and bamboozled. All is working nice! I really love bamboozled! But we add to BHR Team and SubTeam right  now. When I using "client.employee.all" I don't see all information about users. I see in BambooHR but not by script - client.employee.all.

When I check client.employee.job_info I get:

/usr/local/rvm/gems/ruby-2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:18:in `parse': The document "" does not have a valid root (MultiXml::ParseError)

Even I reinstall mutli_xml gem.

Could you help me?

Best,
Rafal

**Comment by kamyk** [comment]
When I'm trying:

client.employee.find(ID, fields = :all) - works
client.employee.all - works 

That two above have two different results. In first one I see more details. But not all fields.

I see here more details but 
client.employee.job_info(ID) - I see result but with error:

does not have a valid root (MultiXml::ParseError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/multi_xml-0.5.5/lib/multi_xml.rb:138:in `parse'
	from /root/USERS/lib/bamboozled/api/base.rb:40:in `rescue in request'
	from /root/USERS/lib/bamboozled/api/base.rb:37:in `request'
	from /root/USERS/lib/bamboozled/api/employee.rb:29:in `block (2 levels) in <class:Employee>'
	from rafal.rb:19:in `main'
	from rafal.rb:24:in `<main>'

Any idea why?

Best,
Rafal

**Comment by juls** [comment]
This looks very similar to issue #5 and my issue with employmentStatus tabular data.

I fixed this in juls/bamboozled@e714ef4; could you try if it works for you, too?

**Comment by chrisman** [comment]
Looks like this was closed in #40
