### ISSUE TITLE
End of file reached

### ISSUE THREAD

**Issue by tmosmant** [Skookum/bamboozled#34]
Hi, since a week I'm getting the following error without any stacktrace after a `client.employee.all` call:

```
================================================================================
scheduler caught exception:
end of file reached

================================================================================
```

Any thought? 🙏

**Comment by ruprict** [comment]
Cannot reproduce. Please supply more info about your use case.

**Comment by tmosmant** [comment]
It's been a while 😄It works now: I think my api key expired somehow. Sorry I didn't give you an update!
