### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by cabello** [Skookum/bamboozled#44]
Hi 👋 

Just found this project while visiting https://www.bamboohr.com/api/documentation/bindings.php and in few minutes I was quickly able to use `client.employee.all` with success! 🎉 

Although things like:

```ruby
pry(main)> client.time_off.whos_out('2018-01-01', Time.now)
# bunch of time off structured data
..."start\":\"2019-01-11\",\"end\":\"2019-01-11\"},{\"id\":3000,\"type\":\"timeOff\",\"employeeId\":111,\"name\":\"John Doe\",\"start\":\"2019-01-11\",\"end\":\"2019-01-17\"}] does not have a valid root
from /Users/john/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/multi_xml-0.6.0/lib/multi_xml/parsers/rexml.rb:18:in `parse'
Caused by NoMethodError: undefined method `with_indifferent_access' for #<Array:0x00007fbf46451098>
from /Users/john/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bamboozled-0.1.0/lib/bamboozled/api/base.rb:42:in `request'
```

This seems to be because the response is an array but it assumed to be a hash, hence the `with_indifferent_access` call.

I also noticed that the latest release on Rubygems.org is from June 14, 2016, while looking through commits I see lots of development happening recently.

What's the status of this gem, is it accepting pull requests? Any plans on releasing newer versions to Rubygems? Should we fork away?

Thanks for you hard work 💜

**Comment by chrisman** [comment]
@cabello 👋 

We are accepting issues and pull requests, and are also having a discussion right now amongst ourselves about how best to support this project. so, stay tuned!

**Comment by splybon** [comment]
@chrisman can we close you think?

**Comment by cabello** [comment]
I integrated with the calendar using the feed URL and icalendar Ruby gem. The API had scoping issues and it was hard for us to retrieve the information we needed.
