### ISSUE TITLE
🚀Update json gem dependency to allow 2.2.0

### ISSUE THREAD

**Issue by danhealy** [Skookum/bamboozled#64]
Changing the dependency from `~> 1.8` to `> 1.8` or `['>= 1.8', '< 3.0']` should be sufficient, the [changes](https://github.com/flori/json/blob/master/CHANGES.md) between these versions are minor.

**Comment by rbroemeling** [comment]
This old dependency lock is actually causing a dependency loop for me at the moment. Is there a reason that bamboozled has an extremely hard dependency on specifically json v1.8.6, or can it trivially change to be a lot looser of a dependency and thus allow a lot more flexibility?

**Comment by splybon** [comment]
@danhealy I'm closing since we fixed this with 0.3.0
